package constant

const (
	RK_USER_ACCESS_TOKEN_SESSION_ID  = "USER:ACCESS_TOKEN_SESSION_ID:"  // ACCESS TOKEN SESSION ID
	RK_USER_REFRESH_TOKEN_SESSION_ID = "USER:REFRESH_TOKEN_SESSION_ID:" // REFRESH TOKEN SESSION ID
)
