name: lark_api_gateway
server_id: 1
port: 8088
log: "./configs/logger.yaml"
etcd:
  endpoints: ["lark-etcd:12379"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
redis:
  address: ["lark-redis:63791"]
  db: 0
  password: lark2022
  prefix: "LK:"
auth_server:
  name: lark_auth_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
jaeger:
  host_port: "lark-jaeger:6831"
  sampler_type: "const"
  param: 1
  log_spans: true
  buffer_flush_interval: 1
  max_packet_size: 0
  enabled: false